name: Auto Comment on Issue Open

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Add Comment to Opened Issue
      run: |
        COMMENT=$(cat <<EOF
        {
          "body": "ðŸ™Œ Thank you for bringing this issue to our attention! We appreciate your input and will investigate it as soon as possible. \n\nFeel free to join our community on [Discord](https://discord.gg/9mZnkTRFFe) to discuss more!"
        }
        EOF
        )
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
          -d "$COMMENT")
        cat response.json
        if [ "$RESPONSE" -ne 201 ]; then
          echo "Failed to add comment on issue open"
          exit 1
        fi

    - name: Assign Issue to User
      run: |
        ASSIGNEES=$(cat <<EOF
        {
          "assignees": ["UTSAVS26"]
        }
        EOF
        )
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
          -d "$ASSIGNEES")
        cat response.json
        if [ "$RESPONSE" -ne 201 ]; then
          echo "Failed to assign user to issue"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
