name: directory_writer
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Write Project-Structure.md
        run: |
          scripts/build_directory_md.py 2>&1 | tee Project-Structure.md
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Update Project-Structure.md
        run: |
          git add Project-Structure.md
          git commit -am "updating Project-Structure.md" ||  true
          git push --force origin HEAD:$GITHUB_REF || true